# Generated by Django 2.2.1 on 2019-07-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superstore',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
